### ISSUE TITLE
整个工程能运行起来，但是单个组件运行不起来

### ISSUE THREAD

**Issue by dazhiyu** [tome34/frameDemoMo2#20]
报 Cause: method ID not in [0, 0xffff]: 65536

        isModule = true
        moduleShopMall = true
        moduleShopCart = true
        moduleWelfare = true
        moduleCommonUi = true

都设置了

**Comment by CharlesZqikai** [comment]
同样遇到了这个问题 @tome34

**Comment by CharlesZqikai** [comment]
![1552361713(1)](https://user-images.githubusercontent.com/13851160/54172967-ed753c80-44ba-11e9-87fb-2a03261b981c.jpg)
已解决 需要在单个组件的build.gradle中开启multiDexEnabled = true
